#!/bin/tcsh -f
setenv SCMAXHEAP 120000
unlimit stack
set options = "-no-assert -compile -c -alias -inline -sra -mlpagator-depth-limit 1"
foreach b (particle saddle)
  foreach d (FF FR RF RR)
    rm -f $b-$d-stalingrad.text
    unbuff >$b-$d-stalingrad.text time stalingrad ${options} $b-$d-stalingrad&
    end
  end

set options = "-no-assert -compile -c -alias -inline -sra -mlpagator-depth-limit 1 -imprecise-inexacts"
foreach b (probabilistic-lambda-calculus probabilistic-prolog)
  foreach d (F R)
    rm -f $b-$d-stalingrad.text
    unbuff >$b-$d-stalingrad.text time stalingrad ${options} $b-$d-stalingrad&
    end
  end

set options = "-no-assert -compile -c -alias -inline -sra -mlpagator-depth-limit 1"
foreach d (Fs R)
  rm -f mlp-$d-stalingrad.text
  unbuff >mlp-$d-stalingrad.text time stalingrad ${options}\
    mlp-$d-stalingrad&
  end
