#!/bin/tcsh -f
unlimit stack
set runs=(0)
cp -i common-hips-autograd.py common_hips_autograd.py
cp -i common-pytorch.py common_pytorch.py

foreach e (particle saddle)
  foreach d (FF FR RF RR)
    foreach run ($runs)
      echo $e-$d HIPS-Autograd $run
      time python $e-$d-hips-autograd.py
      end
    end
  foreach run ($runs)
    echo $e-RR Torch $run
    rm -f /tmp/script
    echo >/tmp/script "#\!/bin/bash"
    echo >>/tmp/script ". /home/qobi/torch/install/bin/torch-activate"
    echo >>/tmp/script "th $e-RR-torch.lua"
    chmod +x /tmp/script
    time /tmp/script
    rm -f /tmp/script
    end
  end

foreach e (probabilistic-lambda-calculus probabilistic-prolog)
  foreach d (F R)
    foreach run ($runs)
      echo $e-$d HIPS-Autograd $run
      time python $e-$d-hips-autograd.py
      end
    end
  foreach run ($runs)
    echo $e-R PyTorch $run
    time python $e-R-pytorch.py
    end
  foreach run ($runs)
    echo $e-RR Torch $run
    rm -f /tmp/script
    echo >/tmp/script "#\!/bin/bash"
    echo >>/tmp/script ". /home/qobi/torch/install/bin/torch-activate"
    echo >>/tmp/script "th $e-R-torch.lua"
    chmod +x /tmp/script
    time /tmp/script
    rm -f /tmp/script
    end
  end

foreach d (Fs R)
  foreach run ($runs)
    echo mlp-$d HIPS-Autograd $run
    time python mlp-$d-hips-autograd.py
    end
  end

foreach run ($runs)
  echo mlp-R PyTorch $run
  time python mlp-R-pytorch.py
  end

foreach run ($runs)
  echo mlp-R Torch $run
  rm -f /tmp/script
  echo >/tmp/script "#\!/bin/bash"
  echo >>/tmp/script ". /home/qobi/torch/install/bin/torch-activate"
  echo >>/tmp/script "th mlp-R-torch.lua"
  chmod +x /tmp/script
  time /tmp/script
  rm -f /tmp/script
  end

rm -f common_hips_autograd.py
rm -f common_pytorch.py
rm -f *.pyc
